export const APP_INIT = 'APP_INIT'
export const APP_SET_VERSION = 'APP_SET_VERSION'

export const WINDOW_SET_SIZES = 'WINDOW_SET_SIZES'
export const SYSTEM_INIT = 'SYSTEM_INIT'

/**
 * auth
 */
export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_SET_DATA = 'AUTH_SET_DATA'
export const AUTH_CLEAR_DATA = 'AUTH_CLEAR_DATA'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_LOG_IN = 'AUTH_LOG_IN'
export const AUTH_REFRESH = 'AUTH_REFRESH'
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT'
export const AUTH_CHECK = 'AUTH_CHECK'

/**
 * user
 */
export const USER_INIT = 'USER_INIT'
export const USER_SET_DATA = 'USER_SET_DATA'
export const USER_SET_SYSTEM_DATA = 'USER_SET_SYSTEM_DATA'
export const USER_SET_CITY = 'USER_SET_CITY'
export const USER_SET_COUNTRY = 'USER_SET_COUNTRY'
export const USER_SET_ADMIN_COMMUNITIES = 'USER_SET_ADMIN_COMMUNITIES'
export const USER_SET_ADMIN_PLACES = 'USER_SET_ADMIN_PLACES'
export const USER_SET_ADMIN_EVENTS = 'USER_SET_ADMIN_EVENTS'
export const USER_CLEAR_DATA = 'USER_CLEAR_DATA'

export const USER_UPDATE_CITY = 'USER_UPDATE_CITY'
export const USER_UPDATE_COUNTRY = 'USER_UPDATE_COUNTRY'
export const USER_LOAD_SELF_DATA = 'USER_LOAD_SELF_DATA'
export const USER_LOAD_SYSTEM_DATA = 'USER_LOAD_SYSTEM_DATA'
export const USER_LOAD_ADMIN_COMMUNITIES = 'USER_LOAD_ADMIN_COMMUNITIES'
export const USER_LOAD_ADMIN_PLACES = 'USER_LOAD_ADMIN_PLACES'
export const USER_LOAD_ADMIN_EVENTS = 'USER_LOAD_ADMIN_EVENTS'

/**
 * account
 */
export const ACCOUNT_SET_ONLINE = 'ACCOUNT_SET_ONLINE'
export const ACCOUNT_SET_OFFLINE = 'ACCOUNT_SET_OFFLINE'

/**
 * modal
 */
export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'
export const MODAL_CLOSE_ALL = 'MODAL_CLOSE_ALL'
export const MODAL_SET_LOCK = 'MODAL_SET_LOCK'


export const APPBAR_UPDATE_BY_CODE = 'APPBAR_UPDATE_BY_CODE'
export const APPBAR_UPDATE_BY_ROUTER = 'APPBAR_UPDATE_BY_ROUTER'

export const APPMENU_UPDATE = 'APPMENU_UPDATE'
export const APPMENU_UPDATE_MA = 'APPMENU_UPDATE_MA'

export const FORMS_M_SET_MODEL = 'FORMS_M_SET_MODEL'
export const FORMS_A_SET_MODEL = 'FORMS_A_SET_MODEL'

export const REGISTER_SET_DATA = 'REGISTER_SET_DATA'
export const REGISTER_CLEAR_DATA = 'REGISTER_CLEAR_DATA'


export const NOTIFICATIONS_SET_ENABLED = 'NOTIFICATIONS_SET_ENABLED'
export const NOTIFICATIONS_SET_SOUND_ENABLED = 'NOTIFICATIONS_SET_SOUND_ENABLED'